Repository CourseDesign/conev-sync, pull requests merged in 2020-09, with the labels that each got.

#12 feature/fix_install_to_prepublish_script
  package.json
  package/conev-sync-core/package.json
  package/conev-sync-json-source/package.json
Labels: bug

#18 feature/publish_1_0_4
  package.json
Labels: bug

#17 feature/change export
  package.json
  src/index.ts
Labels: bug

#19 feat: documentation
  README.md
  package.json
Labels: documentation

#21 feat:use cache
  README.md
  package/conev-sync-core/src/cache/cache.ts
  package/conev-sync-core/src/config/config.spec.ts
  package/conev-sync-core/src/config/config.ts
  package/conev-sync-core/tsconfig.json
  package/conev-sync-json-source/tsconfig.json
  script/change-package.js
  tsconfig.json
Labels: enhancement

#23 publish_1_0_5
  package.json
  package/conev-sync-core/package.json
Labels: enhancement

#22 Version 1.0.5
  README.md
  package.json
  package/conev-sync-core/package.json
  package/conev-sync-core/src/cache/cache.ts
  package/conev-sync-core/src/config/config.spec.ts
  package/conev-sync-core/src/config/config.ts
  package/conev-sync-core/tsconfig.json
  package/conev-sync-json-source/tsconfig.json
  script/change-package.js
  src/index.ts
  tsconfig.json
Labels: documentation, enhancement

#24 Version 1.0.5 (#22)
  README.md
  package.json
  package/conev-sync-core/package.json
  package/conev-sync-core/src/cache/cache.ts
  package/conev-sync-core/src/config/config.spec.ts
  package/conev-sync-core/src/config/config.ts
  package/conev-sync-core/tsconfig.json
  package/conev-sync-json-source/tsconfig.json
  script/change-package.js
  src/index.ts
  tsconfig.json
Labels: documentation, enhancement
